### PR TITLE
vanilla structure generator

### PR DESCRIPTION
**Pull request by Minatocraft**
command or tools that can generate vanilla structures.
[the list of the structures.](https://minecraft.fandom.com/wiki/Generated_structures)

### CODE REVIEW

**Comment by SIsilicon** [comment]
So what does this pull request add?

**Comment by Minatocraft** [comment]
> So what does this pull request add?

I don't understand a thing in GitHub. I asked you on Twitter if you accept suggestions and you told me to create a feature request here.
If this is the right place for suggestions, what I meant was to add a command that allows you to generate villages or any vanilla structure.

**Comment by SIsilicon** [comment]
You make pull requests when you actually add something yourself. Best to make an issue to make your feature request. Closing this one.

**Comment by SIsilicon** [comment]
Also, I think the structure command allows you to load vanilla structures does it not?

**Comment by Minatocraft** [comment]
> Also, I think the structure command allows you to load vanilla structures does it not?

no you need to save it first

**Pull request closed without merging**
